name: surf_flutter_study_jam_2023
description: Surf Flutter Study Jam 2023.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  elementary: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Cera
      fonts:
        - asset: assets/fonts/CeraRoundPro-Thin.otf
        - asset: assets/fonts/CeraRoundPro-Light.otf
        - asset: assets/fonts/CeraRoundPro-Regular.otf
        - asset: assets/fonts/CeraRoundPro-Medium.otf
        - asset: assets/fonts/CeraRoundPro-Bold.otf
        - weight: 400